export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY"